exclude: [
  .git/,
  .idea/,
  .run/,
  node_modules/,
  ruby_modules/,
  assets/js/,
  assets/img/cover/,
  assets/img/site/,
  LICENSE.md,
  README.md,
  CONTRIBUTING.md,
  package.json,
  terserconfig.json,
  tsconfig.json,
  Gemfile,
  Gemfile.lock,
  yarn.lock,
  yarn-error.log,
  assets/pagefind/,
  assets/pagefind-unity-docs/,
]
